name: SwiftCamTools
options:
  bundleIdPrefix: com.swiftcamtools
  deploymentTarget:
    iOS: 17.0
  transitivelyLinkDependencies: true
configs:
  Debug: debug
  Release: release
packages:
  SwiftCamToolsKit:
    path: Packages/SwiftCamToolsKit
  Collections:
    url: https://github.com/apple/swift-collections.git
    from: 1.1.0
  Algorithms:
    url: https://github.com/apple/swift-algorithms.git
    from: 1.2.0
  MetalPetal:
    url: https://github.com/MetalPetal/MetalPetal.git
    from: 2.8.0
settings:
  base:
    SWIFT_VERSION: 5.9
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
targets:
  SwiftCamTools:
    type: application
    platform: iOS
    sources:
      - path: Apps/SwiftCamToolsApp
    resources:
      - path: Resources/Assets.xcassets
    info:
      path: Apps/SwiftCamToolsApp/Info.plist
      properties:
        UILaunchScreen: { UIColorName: Background }
        UIRequiredDeviceCapabilities:
          - video-camera
          - metal
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftcamtools.app
    dependencies:
      - package: SwiftCamToolsKit
      - package: Collections
      - package: Algorithms
      - package: MetalPetal
  SwiftCamToolsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/SwiftCamToolsAppTests
    dependencies:
      - target: SwiftCamTools
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiftcamtools.app.tests
